ALTER TABLE wallet
ADD COLUMN messages_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE wallet
ADD COLUMN minutes_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE wallet
ADD COLUMN data_count REAL NOT NULL DEFAULT 0;
